project:
  type: website
  output-dir: docs

website:
  title: "European Tech Job Market Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: quarto/report.qmd
        text: Report
      - href: quarto/slides.qmd
        text: Slides

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
